server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-ith-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: client-microservice
          uri: lb://client-microservice
          predicates:
            - Path=/api/clients/**, /api/reportes/**
        - id: logs-microservice
          uri: lb://logs-microservice
          predicates:
            - Path=/api/logs/**, /api/logs/reportes/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
