server:
  port: 8001
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: ${GITHUB_URI}
          search-paths: config-data
          username: ${GITHUB_USER}
          password: ${GITHUB_TOKEN}
  application:
    name: config-services
